# Generated by Django 5.1.6 on 2025-03-06 20:23

import colaboradores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id_colaborador', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[colaboradores.models.valida_cpf])),
                ('nome', models.CharField(max_length=100)),
                ('dt_nascimento', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Colaboradores',
                'db_table': 'Colaboradores',
            },
        ),
    ]
