# Generated by Django 5.1.6 on 2025-03-06 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreasTecnologicas',
            fields=[
                ('id_area_tecnologica', models.AutoField(primary_key=True, serialize=False)),
                ('area_tecnologica', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Áreas Tecnológicas',
                'db_table': 'AreasTecnologicas',
            },
        ),
        migrations.CreateModel(
            name='Financiadores',
            fields=[
                ('id_financiador', models.AutoField(primary_key=True, serialize=False)),
                ('financiador', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Financiadores',
                'db_table': 'Financiadores',
            },
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id_projeto', models.AutoField(primary_key=True, serialize=False)),
                ('projeto', models.CharField(max_length=100)),
                ('coordenador', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('inicio_vigencia', models.DateField()),
                ('fim_vigencia', models.DateField()),
                ('valor', models.FloatField()),
                ('qtd_membros', models.IntegerField(default=0)),
                ('equipe', models.ManyToManyField(blank=True, db_table='EquipeProjeto', related_name='equipe', to='colaboradores.colaboradores')),
                ('id_area_tecnologica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.areastecnologicas')),
                ('id_financiador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.financiadores')),
            ],
            options={
                'verbose_name_plural': 'Projetos',
                'db_table': 'Projetos',
            },
        ),
    ]
